# travis-ci 
os: linux
dist: xenial

language: node_js
node_js:
- '8'
- '10'
  
git:
  quiet: true

cache:
  directories:
  - node_modules

before_install:
- npm update
- cd web

install:
- npm install
script:
- npm run test
